[profile.local]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.15'
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'seaport/=lib/seaport/',
]
# via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config